version: '3.8'

services:
  portfolio:
    build: .
    container_name: portfolio-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - portfolio-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.local`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

  # Optional: Add a reverse proxy for production-like setup
  nginx-proxy:
    image: nginx:alpine
    container_name: portfolio-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - portfolio
    networks:
      - portfolio-network
    profiles:
      - production

networks:
  portfolio-network:
    driver: bridge

volumes:
  ssl-certs:
